export default {
  ATL: 'Atlanta Hawks',
  BOS: 'Boston Celtics',
  CHA: 'Charlotte Hornets',
  CHI: 'Chicago Bulls',
  CLE: 'Cleveland Cavaliers',
  DAL: 'Dallas Mavericks',
  DEN: 'Denver Nuggets',
  DET: 'Detroit Pistons',
  GS: 'Golden State Warriors',
  HOU: 'Houston Rockets',
  IND: 'Indiana Pacers',
  LAC: 'LA Clippers',
  LAL: 'LA Lakers',
  MEM: 'Memphis Grizzlies',
  MIA: 'Miami Heat',
  MIL: 'Milwaukee Bucks',
  MIN: 'Minnesota Timberwolves',
  BK: 'Brooklyn Nets',
  NO: 'New Orleans Pelicans',
  NY: 'New York Knicks',
  ORL: 'Orlando Magic',
  PHI: 'Philadelphia 76ers',
  PHX: 'Phoenix Suns',
  POR: 'Portland Trail Blazers',
  SA: 'San Antonio Spurs',
  SAC: 'Sacramento Kings',
  TOR: 'Toronto Raptors',
  UTH: 'Utah Jazz',
  WSH: 'Washington Wizards',
};
